### ISSUE TITLE
Function return_result() fails

### ISSUE THREAD

**Issue by dave39339** [tubaguner/BMI-Calculator#3]
"return_label" variable in function return_result() (file: bmicalculator.py) seem to be unknown... Should it be "result_label" instead?

**Comment by dave39339** [comment]
Not really sure what useful thing the function return_result() supposed to do, one can either comment it out or fix that return_label issue if it is needed for some reason.

**Comment by dave39339** [comment]
See:
https://github.com/tubaguner/BMI-Calculator/blame/b03239c2955b68d00e3d210ac0cb7b6f6af143fb/bmicalculator.py#L24

**Comment by tubaguner** [comment]
I commented it out as you said, still didn't work. Maybe I should add something to result_label to get the output?

**Comment by dave39339** [comment]
This was one thing to be fixed. Wait for other issues to come. :)

**Comment by tubaguner** [comment]
> See: https://github.com/tubaguner/BMI-Calculator/blame/b03239c2955b68d00e3d210ac0cb7b6f6af143fb/bmicalculator.py#L24

Still didn't work. It doesn't recognize "return_label"

**Comment by dave39339** [comment]
There is no such thing "return_label". You have a similar thing, but it is called "result_label".
There is no GUI component that is called return_label in the program.
There is result_label, weight_entry, weight_var, calculate_button... etc., but "result_label" is a variable you try to reference but python has no idea what it is. Just comment it out if unsure, it is not crucial.
I personally would comment out "return_result()" in the function calculate_bmi_value() and get rid of "return_result()" completely, I have no idea what it supposed to do. I can guess, but it doesn't seem to be that useful. :)

**Comment by dave39339** [comment]
Btw. we are fixing a non-crucial function, simply comment it out during tests and comment it in after the other fixes were implemented. Running this function as is may lead to python crashing... :)
